ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_CREATED';
ALTER TABLE "users" ADD COLUMN     "blockedAt" TIMESTAMP(3),
ADD COLUMN     "blockedReason" TEXT;
