ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE 'RENT_BILL_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'RENT_DUE';
ALTER TYPE "NotificationType" ADD VALUE 'LISTING_EXPIRED';
ALTER TYPE "AuditAction" ADD VALUE 'APPLICATION_EXPIRED';
ALTER TYPE "AuditAction" ADD VALUE 'PROPERTY_EXPIRED';
