import PDFDocument from 'pdfkit'
import { APP_NAME } from '../../utils/sendEmail'
import { describePeriod, formatDay } from './payment.utils'

export interface IReceiptData {
    id: string
    amount: number
    currency: string
    periodNumber: number
    periodStart: Date
    periodEnd: Date
    paidAt: Date
    stripePaymentIntentId: string | null
    tenant: { name: string; email: string }
    owner: { name: string }
    property: { title: string; address: string; city: string }
    room: { name: string }
}

const money = (amount: number, currency: string) => `${currency} ${amount.toLocaleString('en-US')}`

// A one-page PDF receipt for a PAID rent payment (emailed, and downloadable from GET /payment/:id/receipt)
export const generatePaymentReceipt = (data: IReceiptData): Promise<Buffer> =>
    new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 50 })
        const chunks: Buffer[] = []

        doc.on('data', (chunk: Buffer) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', reject)

        const left = 50
        const width = doc.page.width - 100

        doc.fontSize(20).font('Helvetica-Bold').fillColor('#0f766e').text(APP_NAME, left, 50)
        doc.fontSize(12).font('Helvetica').fillColor('#64748b').text('Rent payment receipt')
        doc.moveDown(1.5)

        doc.fontSize(10).fillColor('#0f172a')
        doc.text(`Receipt no: ${data.id}`)
        doc.text(`Paid on: ${formatDay(data.paidAt)}`)
        doc.text(`Payment reference: ${data.stripePaymentIntentId ?? '-'}`)
        doc.moveDown(1.5)

        const rows: [string, string][] = [
            ['Tenant', `${data.tenant.name} (${data.tenant.email})`],
            ['Owner', data.owner.name],
            ['Property', data.property.title],
            ['Address', `${data.property.address}, ${data.property.city}`],
            ['Room', data.room.name],
            ['Rent period', `Month ${data.periodNumber}: ${describePeriod(data)}`],
            ['Paid via', 'Stripe (card)'],
        ]

        for (const [label, value] of rows) {
            const y = doc.y
            doc.font('Helvetica').fillColor('#64748b').text(label, left, y, { width: 120 })
            doc.font('Helvetica')
                .fillColor('#0f172a')
                .text(value, left + 130, y, { width: width - 130 })
            doc.moveDown(0.6)
        }

        doc.moveDown(1)
        doc.moveTo(left, doc.y)
            .lineTo(left + width, doc.y)
            .strokeColor('#e2e8f0')
            .stroke()
        doc.moveDown(0.8)

        const totalY = doc.y
        doc.font('Helvetica-Bold')
            .fontSize(13)
            .fillColor('#0f172a')
            .text('Total paid', left, totalY)
        doc.text(money(data.amount, data.currency), left, totalY, { width, align: 'right' })
        doc.moveDown(3)

        doc.font('Helvetica')
            .fontSize(9)
            .fillColor('#94a3b8')
            .text(
                `This receipt was generated by ${APP_NAME}. Keep it for your records.`,
                left,
                doc.y,
                { width, align: 'center' },
            )

        doc.end()
    })
